# Generated by Django 5.0 on 2023-12-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('url', models.URLField(verbose_name='Ссылка на страницу')),
                ('link_type', models.CharField(choices=[('website', 'Веб-сайт'), ('book', 'Книга'), ('article', 'Статья'), ('music', 'Музыка'), ('video', 'Видео')], default='website', max_length=255, verbose_name='Тип ссылки')),
                ('preview_image', models.URLField(blank=True, verbose_name='Картинка превью')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='collections', to='main.bookmark')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
